# Generated by Django 4.2.1 on 2023-09-04 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWeb', '0015_remove_order_message_remove_order_payment_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_remove_cartitems_cart_remove_cartitems_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingadress',
            name='address2',
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to='ecomWeb.product')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
