# Generated by Django 4.2.1 on 2023-05-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('Standard(54-18)', 'Standard(54-18)'), ('Extra Small(52-16)', 'Extra Small(52-16)'), ('Small(54-16)', 'Small(54-16)')], default='Standard(54-16)', max_length=100),
        ),
    ]
