# Generated by Django 4.2.1 on 2023-06-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWeb', '0004_remove_cartitems_cart_remove_cartitems_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='glasses_type',
            field=models.CharField(choices=[('eyeglasses', 'Eyeglasses'), ('sunglasses', 'Sunglasses')], default='Eyeglasses', max_length=80),
        ),
        migrations.AddField(
            model_name='product',
            name='include_offer',
            field=models.BooleanField(default=False),
        ),
    ]
