# Generated by Django 4.2.1 on 2023-06-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWeb', '0005_product_discount_price_product_glasses_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='lower_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='people_img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='upper_img',
            field=models.URLField(),
        ),
    ]
