# Generated by Django 4.2.1 on 2023-06-06 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWeb', '0006_alter_product_lower_image_alter_product_people_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='first_long_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='last_long_product',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='lower_image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='people_img',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='upper_img',
            field=models.URLField(null=True),
        ),
    ]
