# Generated by Django 4.2.1 on 2023-06-10 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecomWeb', '0008_cart_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=80)),
                ('lname', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=100)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('total_price', models.FloatField()),
                ('payment_id', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('Pending ', 'Pending'), ('Out for Shipping', 'Out for Shipping'), ('Delivered', 'Delivered')], default='Pending', max_length=100)),
                ('message', models.TextField(null=True)),
                ('tracking_no', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ecomWeb.product')),
                ('user', models.OneToOneField(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
