# Generated by Django 4.2.1 on 2023-06-13 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomWeb', '0012_buynow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buynow',
        ),
    ]
